name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Test, Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 18.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix['node-version'] }}
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Build Library
        run: npm run build --workspaces --if-present
      - name: Run Tests
        run: npm test --workspaces --if-present
      - name: Prepare modules
        run: node release/prepareModule.js
      - name: Release
        run: npm run release --workspaces
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: github-actions@github.com
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: github-actions@github.com
          CI: true
